#设置开发环境
# 应用名称
# 应用服务 WEB 访问端口
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bylw?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Gepoint
    redis:
      host: 127.0.0.1
      port: 6379
      pcmassword:
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1ms
      database: 0
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
wjq:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
server:
  port: 8081
fdfs:
  so-Timeout: 1501 #socket连接超时时长
  connectTimeout: 601 #连接tracker服务器超时时长
  reqHost: 121.41.164.125   #nginx访问地址
  reqPort: 8888              #nginx访问端口
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 121.41.164.125:22122


