#设置开发环境
# 应用名称
# 应用服务 WEB 访问端口
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bylw?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Gepoint
    redis:
      host: 127.0.0.1
      port: 6379
      pcmassword:
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1ms
      database: 0
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
wjq:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
server:
  port: 8081


